#+ summary: byidref2
#+ endpoint_in_url: False
#+ endpoint: https://scienceplus.abes.fr/sparql
#+ tags:
#+   - identifier

SELECT ?oeuvre ?titre ?role  
WHERE 
 {  
      OPTIONAL { ?s ?p ?_idrefid }
      ?oeuvre dcterms:title ?titre ; vivo:relatedBy [vivo:relates ?idrefuri ; v:hasRole ?role] .
      FILTER(?idrefuri = URI(CONCAT('http://www.idref.fr/', ?_idrefid, '/id')))
 }
 LIMIT 10