#+ summary: byidref
#+ endpoint_in_url: False
#+ endpoint: https://scienceplus.abes.fr/sparql
#+ tags:
#+   - identifier

# cf. https://github.com/CLARIAH/grlc/issues/322#issuecomment-796003965

# Example : 184032997 (idref)

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX v: <http://www.w3.org/2006/vcard/ns#>

SELECT ?oeuvre ?titre ?role  
WHERE 
 {  
      OPTIONAL { ?s ?p ?_idrefid }
      ?oeuvre dcterms:title ?titre ; vivo:relatedBy [vivo:relates ?idrefuri ; v:hasRole ?role] .
      FILTER(?idrefuri = URI(CONCAT('http://www.idref.fr/', ?_idrefid, '/id')))
 }
 LIMIT 10