#+ summary: byorcid
#+ endpoint_in_url: False
#+ endpoint: https://scienceplus.abes.fr/sparql
#+ tags:
#+   - identifier

# cf. https://github.com/CLARIAH/grlc/issues/322#issuecomment-796003965

# Exemple : 0000-0001-5622-7288 (orcid)

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX v: <http://www.w3.org/2006/vcard/ns#>

SELECT ?oeuvre ?titre ?role  
WHERE 
 {  
      OPTIONAL { ?s ?p ?_orcidid }
      ?oeuvre dcterms:title ?titre ; vivo:relatedBy [vivo:relates ?orciduri ; v:hasRole ?role] .
      FILTER(?orciduri = URI(CONCAT('http://orcid.org/', ?_orcidid, '#person')))
 }
 LIMIT 10